-- First, remove the table if it exists
drop table if exists bookmarks;
​
-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text NOT NULL,
  description text,
  rating numeric
);
​
-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  ('Bookmark 1', 'www.website1.com', 'just a website', 4 ),
  ('Bookmark 2', 'www.website2.com', null, 2 ),
  ('Bookmark 3', 'www.website3.com', 'just another website', null ),
  ('Bookmark 4', 'www.website4.com', 'another another website', 3),
  ('Bookmark 5', 'www.website5.com', null, 6 ),
  ('Bookmark 6', 'www.website6.com', null, 4),
  ('Bookmark 7', 'www.website7.com', 'website asdfasdf', null),
  ('Bookmark 8', 'www.website8.com', 'so many websites', 3),
  ('Bookmark 9', 'www.website9.com', 'more websites', 1),
  ('Bookmark 10', 'www.website10.com', null, null),
  ('Bookmark 11', 'www.website11.com', 'all the websites', 10);